version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: db_sql
    restart: always
    env_file: .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$DB_PASSWORD
    ports:
      - "1433:1433"
    networks:
      - webproxy
  webapi:
    build:
      context: PCTASK
      dockerfile: Dockerfile
    image: webapi
    container_name: webapi
    restart: always
    env_file: .env
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"
    networks:
      - webproxy
  front:
    build:
      context: pctask-frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: front_app
    restart: always
    ports:
      - "8080"
    networks:
      - webproxy
networks:
  webproxy:
    external: true
